apis:
  - name: shop
    url: "https://www.cheapshark.com/api/1.0/games?id=304396"

  - name: steam
    url: "http://store.steampowered.com/api/appdetails?appids=3764200&cc=us"

outputFormat: JSON
maxTaskNum: 3
pollingInterval: 10