apis:
  - name: itad
    url: "http://api.isthereanydeal.com/games/info/v2?key=f923b13d2cf4aff250efcc69dc4909a5437131af&id=01974812-da2a-7344-86a1-3fe329430a3a"
  - name: steam
    url: "http://store.steampowered.com/api/appdetails?appids=3764200&cc=us"

outputFormat: JSON
maxTaskNum: 3
pollingInterval: 1